apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers-service
  name: customers-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  strategy: {}
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - image: zzouhal/spring-petclinic-cloud-customers-service
          name: customers-service
          ports:
            - containerPort: 8081
              #hostPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: SPRING_PROFILES_ACTIVE
            - name: MYSQL_CUSTOMERS_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_CUSTOMERS_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PORT
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USERNAME
            - name: MYSQL_CUSTOMERS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_CUSTOMERS_DATABASE
      restartPolicy: Always
status: {}


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: customers-service
status:
  loadBalancer: {}

  
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-customers
 namespace: default
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: customers-service
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80

