apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGV0Y2xpbmlj #mot de passe encodé en base64

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  SPRING_PROFILES_ACTIVE: "docker,mysql"
  MYSQL_HOST: "mysql-petclinic"
  MYSQL_PORT: "3306"
  MYSQL_USERNAME: "root"
  MYSQL_DATABASE: "petclinic"


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-petclinic
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-petclinic
  template:
    metadata:
      labels:
        app: mysql-petclinic
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-petclinic-data
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-petclinic-data
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-petclinic
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
