kubectl delete deployments --all
kubectl delete services --all
kubectl delete statefulsets --all
kubectl delete configmaps --all
kubectl delete secrets --all
kubectl delete persistantvolumes --all
kubectl delete persistantvolumeclaims --all
kubectl delete hpa --all
kubectl delete ingress --all
