apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - image: springcommunity/spring-petclinic-discovery-server
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://discovery-server:8761
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 3
          name: discovery-server
          ports:
            - containerPort: 8761
              hostPort: 8761
              protocol: TCP
          resources:
            limits:
              memory: "536870912"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: SPRING_PROFILES_ACTIVE
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PORT
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery-server
  name: discovery-server
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    app: discovery-server
status:
  loadBalancer: {}


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-discovery
 namespace: default
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: StatefulSet
   name: discovery-server
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80

