apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-server-config
data:
  JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
        - name: tracing-server
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411
          resources:
            limits:
              memory: 512Mi
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: tracing-server-config
                  key: JAVA_OPTS
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: SPRING_PROFILES_ACTIVE
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-server
spec:
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app: tracing-server


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-tracing
 namespace: default
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: tracing-server
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80