apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: visits-service
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  strategy: {}
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - image: zzouhal/spring-petclinic-cloud-visits-service
          name: visits-service
          ports:
            - containerPort: 8082
              #hostPort: 8082
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: SPRING_PROFILES_ACTIVE
            - name: MYSQL_VISITS_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_VISITS_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PORT
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USERNAME
            - name: MYSQL_VISITS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_VISITS_DATABASE
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    app: visits-service
status:
  loadBalancer: {}

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-visits
 namespace: default
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: visits-service
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80
